{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
  {{- with .Values.gateway.clusterIssuer }}
  annotations:
    cert-manager.io/cluster-issuer: {{ . }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  {{- with .Values.gateway.listeners }}
  listeners:
    {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}