apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "base.fullname" . }}
spec:
  provider: aws
  parameters:
    objects: |
{{- range .Values.secretsremote.secrets }}
      - objectName: "{{ .awsSecretName }}"
        objectType: "secretsmanager"
        jmesPath:
{{- range .keys }}
          - path: {{ . }}
            objectAlias: {{ . }}
{{- end }}
{{- end }}
  secretObjects:
    - secretName: '{{ include "base.fullname" . }}-secretsremote'
      type: Opaque
      data:
{{- range .Values.secretsremote.secrets }}
  {{- range .keys }}
        - objectName: {{ . }}
          key: {{ . }}
  {{- end }}
{{- end }}
